require.config({
    paths:{
        jquery:'../lib/jquery-3.2.1',        
        common:'common',
        xcarousel:'../lib/jquery-xcarousel/jquery.xCarousel',
        xzoom:'../lib/jquery-xZoom/jquery.xZoom'
    },
    shim:{
        xcarousel:['jquery'],
        xzoom:['jquery'],
    }
});
